### PR TITLE
Vector tiles decoder

### PR DESCRIPTION
**Pull request by kevinzau**
VectorTile Decoder
This is a functioning [Mapnik Vector Tile](https://github.com/mapbox/vector-tile-spec/tree/master/2.1) decoder with some functionality for filtering through the data. It was created as part of an OpenAcademy project [geotrellis-osm-elevation](https://github.com/geotrellis/geotrellis-osm-elevation/). Known issues are described in some detail in the body of failing test cases.

Functionality:
- Decoding vector tiles into a scala representation
- Filtering for geometries based on fields of the layer or feature it is in
- Alternate constructors for building pieces of the representation and putting them together

Known issues:
- Polygons that intersect themselves seem to raise errors or yield incorrect shapes.
- The current way of dealing with Polygons with holes is INCORRECT. The specification uses negative area which did not translate well to the jts representation that geotrellis's representation is based on. This might be done with a separate command (additional structure to the specification), with computational geometry, etc.

Extensions:
- The encoder should not be too hard to finish. It requires iterating through the data structure, converting back into the vector_tile proto form, and then calling the write bytes function from there

### CODE REVIEW

**Comment by lossyrob** [comment]
@kamicut FYI this is the vector tile reader stuff we were talking about at FOSS4G NA

**Comment by lossyrob** [comment]
@kevinzau can you give a description/overview of the feature in the description of the pull request?

**Comment by kevinzau** [comment]
I've edited the first post to have the description (since that'll make it easy to find.)

**Comment by kamicut** [comment]
@lossyrob thanks for tag. 👍

**Comment by echeipesh** [comment]
Merging this in so I can clean up the project structure for this feature.

**Pull request merged**
