### PR TITLE
Fix Non-Point Pixel + Partial Cell Rasterizer Bug

### PR DESCRIPTION
**Pull request by jamesmcclain**
The issue was that when there were edges which crossed a pixel but whose intersection with the scan rectangle was outside of that pixel, the pixel was not being reported.

Supersedes #1800
Connects #1801

### CODE REVIEW

**Comment by jamesmcclain** [comment]
@zaikin  Thanks for the bug report.  These changes fix the broken test that you provided.  Would you mind testing these changes to see if they fix your original issue?

**Comment by zaikin** [comment]
@jamesmcclain yes, it works. Thx :tada:

**Comment by jamesmcclain** [comment]
Sounds great.  Thanks again for the bug report!

**Comment by lossyrob** [comment]
@zaikin in order for us to use the commit with the unit tests, we'd need you to sign a CLA (as described in our [contributing.md](https://github.com/geotrellis/geotrellis/blob/master/contributing.md)), and re-do that commit with an email that is associated with your github account. Would you be able to do these couple of things? Sorry for the hassle, and thanks for the bug report and contribution!

**Comment by zaikin** [comment]
@lossyrob no problem, i'll do it a bit later today.

**Comment by lossyrob** [comment]
@zaikin thanks! I'm looking to push an RC out today, so if you all that done today, I'll be able to include it in the RC.

**Comment by zaikin** [comment]
@lossyrob i redid commit and sent a signed CLA.

**Comment by jamesmcclain** [comment]
rebasing now

**Comment by jamesmcclain** [comment]
Rebased.

**Comment by lossyrob** [comment]
@zaikin many thanks!

+1 after travis

**Pull request merged**
