### PR TITLE
Added sequence unions for lines, points, polygons and multis

### LINKED ISSUE #893: Add sequence unions on lines sequence and point sequence
Add an implicit class to take a `Seq[Line]` and add a `union` method (or any other collection related operations) so we can do:

```scala
val merged = Seq(l1, l2, l3, l4).union
```

where `l1`, `l2`, ... are of type `Line`

### PR DESCRIPTION
**Pull request by kyeah**
Adds implicit classes for Geometry sequences. Fixes #893.

### CODE REVIEW

**Comment by lossyrob** [comment]
@kyeah nice. Is there other sequence operations we should support? e.g. `intersection`. Let's think about all the sequence operations we should support and implement them in this PR.

**Comment by kyeah** [comment]
union is the only operation with a default (no-arg) implementation, but we can add reduction methods to the Multi geometries and introduce appropriate Results:

```scala
lines.map { line => line.jtsGeom }.reduce[Geometry] {
    (acc, line) => acc.intersection(line)
}
```

Same for `difference` and `symDifference`.

**Comment by lossyrob** [comment]
Did you check the JTS codebase to make sure that's the case (e.g. how union
uses
https://github.com/lossyrob/jts/blob/master/jts/java/src/com/vividsolutions/jts/operation/union/CascadedPolygonUnion.java)?
Some operations are hidden in JTS in the operations and algorithms. If so,
then yup the reduction methodology should work.

**Comment by kyeah** [comment]
There aren't any other collection operations from what I can tell.

**Comment by lossyrob** [comment]
Cool. Then the reduction operations make sense. You'll want to write some benchmarks for them to make sure it's reasonably fast (see the vector-benchmark subproject).

**Comment by kyeah** [comment]
Output from reduction op benchmarks:
```
[info] Average for MultiLine intersection: 1.6644260599793175
[info] Average for MultiLine difference: 0.2829056111352762
[info] Average for MultiLine symDifference: 0.014963880288957688
```
Intersections have a high amount of variability between tests - between 1-5 seconds.

**Comment by lossyrob** [comment]
Try it with a caliper benchmark (like the ones in the benchmark subproject). Should decrease the variability.

**Comment by kyeah** [comment]
```
[info]              benchmark     ms linear runtime                                                                  
[info]         MultiLineUnion  69.74 ==                                                                              
[info]  MultiLineIntersection   2.78 =                                                                               
[info]    MultiLineDifference  38.23 =                                                                               
[info] MultiLineSymDifference 386.32 ===============
```

**Comment by lossyrob** [comment]
Awesome. Thanks.

**Comment by lossyrob** [comment]
@kyeah sorry I didn't catch this initially....this functinoality should go in geotrellis.vector, not geotrellis.vector.op

Can you do that change?

**Comment by lossyrob** [comment]
@kyeah actually, @moradology is going to take care of it, so disregard (but look at the code after his PR to see what needed to be done).

**Pull request merged**
