### PR TITLE
Support for temporal hadoop multiband geotiffs

### PR DESCRIPTION
**Pull request by jasonbeverage**
This PR adds support for hadoop temporal multiband geotiffs to spark-etl.

Changes:
* Changed the MultibandSpaceTimeHadoopOutput to use correctly use MultiBandTile instead of Tile.  
* Added new TemporalMultibandGeoTiffHadoopInput input to spark-etl
* Added new hadoopTemporalMultiBandGeoTiffRDD methods to HadoopSparkContextMethods
* Add TemporalMultiBandGeoTiffInputFormat input format.

### CODE REVIEW

**Comment by lossyrob** [comment]
Thanks @jasonbeverage!

We're having some discussion about which CLA will be required once we complete the move to LocationTech, and before we fully make the move. We have an Azavea CLA which I'm not sure we will require, but since your contributions are becoming more substantial, would you mind signing it in case we do decide to require it? It's a PDF, so you can do a print/scan/email to info@azavea.com, or if you have your signature image you can place it on the PDF and email us.

Here's the individual CLA: http://geotrellis.github.io/files/2014_05_20-GeoTrellis-Open-Source-Contributor-Agreement-Individual.pdf?raw=true

Here's the corporate CLA: http://geotrellis.github.io/files/2012_04_04-GeoTrellis-Open-Source-Contributor-Agreement-Corporate.pdf?raw=true

If you're doing the work as part of company time (i.e. your company owns the copyright), then we'd need the corporate CLA.

Thanks again,
Rob

**Comment by jasonbeverage** [comment]
Just sent over a corporate CLA with myself and @plevy on it.  Let me know if you need anything else!

**Comment by pomadchin** [comment]
:+1:

**Comment by lossyrob** [comment]
Very cool. Thank you!

**Pull request merged**
