### PR TITLE
WIP: Input src in etl and ingest objects

### PR DESCRIPTION
**Pull request by pomadchin**
Currently input crs forces to be equal dest crs. 

- [x] fix inputs crs in Etl and in Ingest objects
- [x] test it on tiles in different projections
  - [x] webmerc (chatta demo)
  - [x] sinus (modis, MOD13Q1: ingested `2015 001 18 03`)
  - [x] utm (lc8: ingested `LC82010352015188LGN00_B2.TIF`)
  - [ ] latlng

### CODE REVIEW

**Comment by pomadchin** [comment]
A curious problem appeared:

```
$ gdalinfo -proj4 all-ones.tif 
Driver: GTiff/GeoTIFF
Files: all-ones.tif
Size is 512, 512
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
PROJ.4 string is:
'+proj=longlat +datum=WGS84 +no_defs '
Origin = (141.706666666666706,-17.520000000000010)
Pixel Size = (0.000833333333333,-0.000833333333333)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( 141.7066667, -17.5200000) (141d42'24.00"E, 17d31'12.00"S)
Lower Left  ( 141.7066667, -17.9466667) (141d42'24.00"E, 17d56'48.00"S)
Upper Right ( 142.1333333, -17.5200000) (142d 8' 0.00"E, 17d31'12.00"S)
Lower Right ( 142.1333333, -17.9466667) (142d 8' 0.00"E, 17d56'48.00"S)
Center      ( 141.9200000, -17.7333333) (141d55'12.00"E, 17d44' 0.00"S)
Band 1 Block=512x4 Type=Float32, ColorInterp=Gray
  NoData Value=-9999
```

The projection read automatically is: 

```
+proj=latlong +datum=WGS84 +to_meter=1.0 
```

For some reason it can't convert extent with that projection, digging into it.

**Comment by lossyrob** [comment]
That is strange. The GeoTiff reader should catch the EPSG code and use the proj4 string here: https://github.com/geotrellis/geotrellis/blob/master/proj4/src/main/resources/nad/epsg#L498

When you say "the projection is read in automatically", how do you mean? You mean if you read in the GeoTiff via `SingleBandGeoTiff` and then print the `crs`?

**Comment by pomadchin** [comment]
@lossyrob from git tags i mean by `RasterMetaData.fromRdd(rdd, layoutScheme)`

Seems like a certain tiff tags bug ._.

**Comment by pomadchin** [comment]
Our parser sets LatLong projection `Model Type Code` to `2`: http://www.remotesensing.org/geotiff/spec/geotiff6.html

**Comment by pomadchin** [comment]
Digging deeper: 

```
$ listgeo all-ones.tif
TIFFReadDirectory: Warning, Unknown field with tag 42113 (0xa481) encountered.
Geotiff_Information:
   Version: 1
   Key_Revision: 1.0
   Tagged_Information:
      ModelTiepointTag (2,3):
         0                 0                 0                
         141.706666666667  -17.52            0                
      ModelPixelScaleTag (1,3):
         0.000833333333333325 0.000833333333333332 0                
      End_Of_Tags.
   Keyed_Information:
      GTModelTypeGeoKey (Short,1): ModelTypeGeographic
      GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
      GeographicTypeGeoKey (Short,1): GCS_WGS_84
      GeogCitationGeoKey (Ascii,7): "WGS 84"
      GeogAngularUnitsGeoKey (Short,1): Angular_Degree
      GeogSemiMajorAxisGeoKey (Double,1): 6378137          
      GeogInvFlatteningGeoKey (Double,1): 298.257223563    
      End_Of_Keys.
   End_Of_Geotiff.

GCS: 4326/WGS 84
Datum: 6326/World Geodetic System 1984
Ellipsoid: 7030/WGS 84 (6378137.00,6356752.31)
Prime Meridian: 8901/Greenwich (0.000000/  0d 0' 0.00"E)
Projection Linear Units: User-Defined (1.000000m)

Corner Coordinates:
Upper Left    (141d42'24.00"E, 17d31'12.00"S)
Lower Left    (141d42'24.00"E, 17d56'48.00"S)
Upper Right   (142d 8' 0.00"E, 17d31'12.00"S)
Lower Right   (142d 8' 0.00"E, 17d56'48.00"S)
Center        (141d55'12.00"E, 17d44' 0.00"S)
```

**Comment by pomadchin** [comment]
Changes by @echeipesh include this changes  #1340
Discussion moved to #1341

**Pull request closed without merging**
