### PR TITLE
Add option to select affected cells in focal ops

### PR DESCRIPTION
**Pull request by dwins**
This is intended to supersede #1430. I'll take a look at the merge conflicts this afternoon. I also ran into some issues with the benchmarks. I've been benchmarking with the existing focal benchmarks in `geotrellis-benchmark` using `sbt "geotrellis-benchmark/testOnly benchmark.geotrellis.raster.op.focal.FocalOperationsBenchmark` . With my branch published using `scripts/publish-local-crossversion.sh` the tests complete with typical results (negligible performance changes relative to what I was seeing on master.)  However, with current master the benchmarking suite hangs on:

```
Running benchmarks for FocalMean on different sizes of tile...
  1 of 2: tiled 256                   ..................................................................................................................................................................................................................................................................................................................................................................................................................................
```

The behavior I'm seeing is that the screen continues to fill up with `.` characters indefinitely (left it running for 15 minutes or so before killing.)  Once I've resolved the merge conflicts perhaps I'll see the same behavior on my branch.

### CODE REVIEW

**Comment by lossyrob** [comment]
@lokifacio can you take a look at this and let us know what you think? Thank you!

**Comment by lossyrob** [comment]
@dwins was this PR based on #1430? Wondering where the commits for that PR are.

**Comment by lokifacio** [comment]
It seems clearer than my solution. Should we include the unit tests I did?

**Comment by lossyrob** [comment]
@lokifacio yes, the more testing the better. Would you like to bring those over? You could checkout dwin's repo and cherry pick the test commits or copy the code over, commit, and then create a new PR that would supersede this one.

**Comment by lossyrob** [comment]
Superseded by #1601

**Pull request closed without merging**
