### PR TITLE
API Renames

### PR DESCRIPTION
**Pull request by pomadchin**
* MultiBand -> Multiband
* MetaData -> Metadata
* multiBand -> multiband
* metaData -> metadata

### CODE REVIEW

**Comment by pomadchin** [comment]
Depends on #1273

**Comment by pomadchin** [comment]
Here https://github.com/pomadchin/geotrellis/pull/3/files is possible to look how it differs from #1273 before its merge.

**Comment by pomadchin** [comment]
I ma curious, should the `SingleBand` be renamed?

**Comment by echeipesh** [comment]
Good catch, yes.

**Comment by pomadchin** [comment]
Closed, created same changes but against master #1295

**Pull request closed without merging**
