### PR TITLE
[WIP] API Renames 

### PR DESCRIPTION
**Pull request by pomadchin**
* MultiBand -> Multiband
* SingleBand -> Singleband
* MetaData -> Metadata
* multiBand -> multiband
* singleBand -> singleband
* metaData -> metadata

It is a #1288 PR but against master branch
Issue: https://github.com/geotrellis/geotrellis/issues/1267

### CODE REVIEW

**Comment by pomadchin** [comment]
Will make it WIP until we can figure out what to do with it

**Comment by pomadchin** [comment]
@lossyrob @echeipesh @jamesmcclain @moradology should this pr also include other api renames? 

* SpatialKey -> GridKey
* SpatialComponent -> GridComponent
* SpaceTimeKey -> TimeGridKey
* RasterRDD[K] -> TileRDD[K]
* MultiBandRasterRDD[K] -> MultiBandTileRDD[K]

**Comment by lossyrob** [comment]
@pomadchin I think so, but I'm not sure. Let's talk about it tomorrow on Gitter to make a decision.

**Comment by pomadchin** [comment]
we decided to make all api renames according to #1267 issue

**Pull request closed without merging**
