### PR TITLE
Update Contributor list

### PR DESCRIPTION
**Pull request by fosskers**
Updated to include core members joined since 2015.

### CODE REVIEW

**Comment by lossyrob** [comment]
Now that we have a bunch of contributors, is it worth trying to keep this list up? This doesn't have everybody.

Maybe have a definition of "core"? Like, people who have contributed to x amount of +/-?

**Comment by fosskers** [comment]
>  is it worth trying to keep this list up?

Perhaps not, the `Contributors` tab does a pretty good job of this already. Core contributors are also easily checkable from the GeoTrellis organization page.

**Comment by lossyrob** [comment]
True. I'm down for deleting this section.

**Comment by fosskers** [comment]
Done!

**Pull request merged**
