### PR TITLE
Break up raster.stats for consistency

### PR DESCRIPTION
**Pull request by notthatbreezy**
This commit breaks up raster.stats into raster.op.stats
and raster.histogram

### CODE REVIEW

**Comment by notthatbreezy** [comment]
Closes #978

**Comment by lossyrob** [comment]
@notthatbreezy the benchmark subproject is broken.

**Comment by notthatbreezy** [comment]
Oops - fixed. The error wasn't showing up even after doing `./buildall.sh`. I did an `./sbt clean` and was able to get the error message.

**Comment by lossyrob** [comment]
+1

**Pull request merged**
