### PR TITLE
Add interpretAs and withNoData methods to Tile

### PR DESCRIPTION
**Pull request by echeipesh**
Fixes: https://github.com/geotrellis/geotrellis/issues/1674

Allows for more flexibility when working around NoData values.

Additionally this expands the capacity of the `ConstantTile` to represent constant tiles other than tiles with `ConstantNoDataHandling` to satisfy the conversions implied by the new API.

TODO:
 - [x] Unit tests for interpret 
 - [x] GeoTiffMultibandTile.interpretAs
 - [x] `Tile.withNoData`
 - [x] Tile concrete classes `noDataValue` constructor overload
 - [x] New API review / discussion

### CODE REVIEW

**Comment by lossyrob** [comment]
Is this WIP until the RFC gets worked out?

**Comment by echeipesh** [comment]
I'd be happy to bundle them together, but they don't have to be. This PR can be merged as is and addresses the issue that spawned it.

**Comment by echeipesh** [comment]
@lossyrob @moradology Ready for review again after `.withNoData` changes. 

One final through is that what is currently `.interpretAs` might be better named `.withCellType`. That name seems consistent with behavior:
 - If we're not  changing underlying data type this just re-wraps the array with new CellType.
 - Otherwise we coerce to the desired cell type and label it with new NoDataHandling

**Comment by lossyrob** [comment]
@echeipesh I think `withCellType` is a bit ambiguous, and might be read as doing the same thing `convert` does. But I've though about this less, so if you are strong +1 on that name I'll follow your lead.

**Comment by moradology** [comment]
I also think `withCellType` seems more ambiguous. Have we considered, as an alternative to `interpretAs`, `reinterpret`?

**Comment by echeipesh** [comment]
I prefer `interpretAs` to `reinterpret`. I thought that `withCellType` has nice symmetry to `withNoData` but lets discount it since its got two votes against it. I'm still not totally happy with `interpretAs`, I'd like to capture the intuition is that this is equivalent of calling `_.toDouble` or `_.toInt` on cell by cell basis.

- `toCellType(IntCells)`
- `asCellType(IntCells)`
- `convertRaw(IntCells)` 
- `convertFromRaw(IntCells)` 
- `reassign(IntCells)`
- `coerce(IntCells)`

**Comment by fosskers** [comment]
Semantic ambiguity could be addressed in docstrings.

**Comment by fosskers** [comment]
+1 `interpretAs`. I think it's the most semantically clear.

**Comment by pomadchin** [comment]
I like the word `coercion` but it usually means an _implicit_ type conversion the word _cast_ used for explicit (correct me if I'm wrong). So probably `interpretAs` or even `cast` (but `cast` looks similar to `convert`). But I see no problems `withCellType` name as well, as for me it means more a `type` _interpretation_ rather than `converting` :)) 
-  +1 `interpretAs`

**Comment by echeipesh** [comment]
Thank you everybody for chiming in on the naming!
For eons let it written, let it be said: `Tile.interpretAs`

**Pull request merged**
