### PR TITLE
Hdfs Range Reads

### PR DESCRIPTION
**Pull request by jbouffard**
This PR adds a rangeRead method to HdfsUtils that allows for reading ranges of bytes.

### CODE REVIEW

**Comment by jbouffard** [comment]
@lossyrob Ready for review.

**Comment by lossyrob** [comment]
@jbouffard there was one build that passed, but another that failed with

```
geotrellis.spark.io.hadoop.HdfsUtilsSpec *** ABORTED ***
[info]   java.io.FileNotFoundException was thrown inside describe("HdfsUtils"), construction cannot continue: "raster-test/data/geotiff-test-files/ls8_int32.tif (No such file or directory)" (HdfsUtilsSpec.scala:14)
```

Not sure how one passed and one didn't, maybe caching?

**Comment by lossyrob** [comment]
@jbouffard will this allow us to implement a streaming Hdfs byte reader, so that we can place large geotiffs on S3 and eventually do a windowed ingest from them? Is that functionality planned for a follow up PR?

**Comment by jbouffard** [comment]
@lossyrob Yes, this is similar to the `readRange` method that we currently have for the `S3Client` [link](https://github.com/geotrellis/geotrellis/blob/master/s3/src/main/scala/geotrellis/spark/io/s3/S3Client.scala#L183). While I don't think we ever officially planned anything, I assumed that's what I'd be doing after I finish up the tasks for 1.0.

**Pull request merged**
