### PR TITLE
WIP: Allow adding entries to SpatialIndex by Extent

### PR DESCRIPTION
**Pull request by dwins**
Addresses #1249. Please don't merge yet, I'm happy with this but have not completed the CLA.

### CODE REVIEW

**Comment by lossyrob** [comment]
@dwins can you tie your email address to your github account? The commit isn't picking up that it's you that made the change; ideally you'd be committing with the same email address that you'd have registered with an Eclipse account that has the CLA of their's signed, and that is tied to your github account.

**Comment by lossyrob** [comment]
There's a couple of `apply` methods in the `SpatialIndex` object that make newing up a spatial index easier on the client if what they have is Iterable of point-like things. This API functionality should be replicated by the Extent capabilities of this feature.

**Comment by lossyrob** [comment]
We currently keep track of a set of `points` inside the instance; this was for some `geotrellis-transit` functionality, and I'm not sure it should be in there. We should probably remove it; if we don't, we should rename it to reflect that they aren't just points. My vote is for removal though.

**Comment by lossyrob** [comment]
A unit test proving this functionality should be made.

**Comment by dwins** [comment]
Associated my email with my github account.  I'll look into the changes you suggested.

**Pull request closed without merging**
