### PR TITLE
Bugfix/1200

### LINKED ISSUE #1200: Geotiff reader fails when using modeltransformation
A Geotiff can specify its georeferencing by using a transformation matrix (in my case, it was written by geotools). The geotrellis reader failed to read due to two issues when determining the model bounds based on this transformation. 
* When multiplying the matrix with a vector, in TiffTags.transformationModelSpace, replaced Array(Array(pixel.x, pixel.y, pixel.z, 1)) with Array(Array(pixel.x),Array( pixel.y),Array( pixel.z),Array( 1)))
* In the matrix multiplication itself (MatrixExtensions.scala) replaced sum += matrix(i)(j) * second(k)(j) with sum += matrix(i)(k) * second(k)(j)

I can provide a file that triggers this issue if necessary.

### PR DESCRIPTION
**Pull request by jdries**
Fixed previous pull request for issue 1200

Closes #1200

### CODE REVIEW

**Comment by lossyrob** [comment]
Great stuff, thank you! I updated the description to say "Closes #1200" so that when this gets merged the issue automatically is closed.

Would you mind signing our CLA? See the Contributer's License Agreement section of: http://geotrellis.io/project-info/contributing/ 

I'm going to look through the GeoTiff spec just to see what went wrong here and how the fix solves it, but otherwise the code looks good to me.

**Comment by lossyrob** [comment]
I made a pull request to this branch with some updates, feel free to discuss them here or on that PR

**Comment by lossyrob** [comment]
Thanks @jdries. Are you OK with merging this in at this point?

**Comment by jdries** [comment]
I've been able to test all of this on a number of files, and everything seems fine. I'll try to get the SLA signed so you can do the merge.

**Comment by lossyrob** [comment]
Hey @jdries, I just realized that, since there's not much code that survived my refactor, the CLA isn't strictly necessary here. So I'm going to merge...thank you for pointing out the issue and the contribution!

**Comment by jdries** [comment]
Thx,


sorry, we're in a bit of a rush over here, so this slipped my mind. Nice to see this got fixed so smoothly.


best regards,

Jeroen


Jeroen Dries
TAP - Centre for Remote Sensing and Earth Observation Processes
VITO NV | Boeretang 200 | 2400 Mol
tel. +32 14 33 55 11 | jeroen.dries@vito.be<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=mailto%3avoornaam.naam%40vito.be>
[cid:image001.jpg@01CDCE3A.4E197A50]<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=http%3a%2f%2fwww.vito.be%2f>[cid:image001.jpg@01CD3F0D.B57AA190]<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=http%3a%2f%2fwww.linkedin.com%2fcompany%2f17947>[cid:image003.jpg@01CD3F0D.B57AA190]<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=http%3a%2f%2ftwitter.com%2f%23%21%2fvitobelgium>[cid:image002.jpg@01CD3F0D.B57AA190]<https://outlook.vito.be/OWA/redir.aspx?C=bkbvq29Z1EO1hvVK0QJMbACOitzQ7c8Ip7CWFVkhZV75OTezDjCIkdDzkCq1rif2MTOFHY6bxtg.&URL=https%3a%2f%2fwww.facebook.com%2fVITObelgium>
________________________________
Van: Rob Emanuele <notifications@github.com>
Verzonden: maandag 30 november 2015 23:24
Aan: geotrellis/geotrellis
CC: Dries Jeroen
Onderwerp: Re: [geotrellis] Bugfix/1200 (#1203)


Merged #1203<https://github.com/geotrellis/geotrellis/pull/1203>.

-
Reply to this email directly or view it on GitHub<https://github.com/geotrellis/geotrellis/pull/1203#event-478294568>.

VITO Disclaimer: http://www.vito.be/e-maildisclaimer

**Pull request merged**
