### PR TITLE
ETL Improvements and other issues fixes

### PR DESCRIPTION
**Pull request by pomadchin**
* https://github.com/geotrellis/geotrellis/issues/1547
* https://github.com/geotrellis/geotrellis/issues/1642
* https://github.com/geotrellis/geotrellis/issues/1641
* https://github.com/geotrellis/geotrellis/issues/1276
* https://github.com/geotrellis/geotrellis/issues/1408

### CODE REVIEW

**Comment by pomadchin** [comment]
@RickMohr and @lossyrob what do you think about clipping by extent?

**Comment by RickMohr** [comment]
If clipping by extent and also transforming coordinates, should the clipping frame be specified in the source or target coordinate system? I think it would be more useful in the target coordinate system. In either case some doc would be important to avoid confusion.

**Comment by pomadchin** [comment]
@RickMohr in the current implementation - the source coordinate system; though I agree with you, let's make it in target coordinate system and need to update docs, thanks!

**Comment by RickMohr** [comment]
Clipping looks good, thanks!

**Comment by pomadchin** [comment]
:0 sorry for that @lossyrob

**Pull request merged**
