### PR TITLE
Change Return Type of RDDFilter

### PR DESCRIPTION
**Pull request by jamesmcclain**
RDDFilter now returns a Seq[KeyBound] instead of an Option[KeyBound].

Tests for the `spark` project all passed locally except for `geotrellis.spark.op.local.spatial.LocalSpatialSpec`.

### CODE REVIEW

**Comment by lossyrob** [comment]
@jamesmcclain can you merge upstream/master into this PR?

**Comment by jamesmcclain** [comment]
It looks like it needs to be rebased.  Doing so now.

**Comment by echeipesh** [comment]
+1

**Comment by jamesmcclain** [comment]
Many thanks.

**Pull request merged**
