### PR TITLE
add multiband foreach to MultibandTile

### PR DESCRIPTION
**Pull request by hjaekel**
This is a pull request for issue #1530 (Multiband foreach method that gives all band values).

### CODE REVIEW

**Comment by lossyrob** [comment]
@hjaekel thank you for the contribution!

Can you please sign the CLAs described here? https://github.com/geotrellis/geotrellis/blob/master/contributing.md#contributor-license-agreements-cla

Also, your commit is not made with an email address that is tied to your github account. Can you please change the commit to use the email that is tied to your github?
https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/
http://stackoverflow.com/questions/750172/change-the-author-of-a-commit-in-git

Thanks!

**Comment by lossyrob** [comment]
@hjaekel I'd like to potentially get this merged in for 0.10.2. Is it possible to get the CLAs to us ASAP? 

Thanks,
Rob

**Comment by hjaekel** [comment]
@lossyrob We will try to get the CLA signed in the next days.

**Comment by lossyrob** [comment]
@hjaekel thanks for the CLA! Merging.

**Pull request merged**
